### ISSUE TITLE
possible NiiVue integration?

### ISSUE THREAD

**Issue by hanayik** [anibalsolon/vscode-neuro-viewer#13]
Hi @anibalsolon, 

This project looks neat. Through the weird ways of the web, I somehow stumbled across it, and thought it might be nice to see how much effort it would be to try adding NiiVue (https://github.com/niivue/niivue) as the renderer. No worries if not, just thought it could be a nice pairing!

**Comment by anibalsolon** [comment]
Hi @hanayik 

Thank you for reaching out- I am sorry for the delayed answer. NiiVue looks really nice, especially about the WebGL2. I would be happy to move to a more robust solution as yours.

How is NiiVue support for fMRI?

**Comment by hanayik** [comment]
Hi @anibalsolon, thanks for the reply. better fMRI support is planned in the near future. 

Currently fMRI volume loading is supported, but it will just show the first volume in the canvas. There isn't a mechanism to scroll volumes yet. 

You can test by dragging and dropping an fMRI time series onto the canvas here: https://niivue.github.io/niivue/features/draganddrop.html (nothing is uploaded anywhere, just reads the data locally)

**Comment by anibalsolon** [comment]
Nice! Yes- I've been working on this feature, and to not put much memory pressure, I was loading just some values at the time, and load more as the user requests. So it got me wonder if NiiVue has an internal API that I could provide the arraybuffer of the new volume to update the visualization. But certainly, MRI first! I will give it a try this weekend.

**Comment by anibalsolon** [comment]
Hey @hanayik I've decided to keep using my custom rendering mechanism as I have more flexibility in how things move internally. My code certainly requires more optimization and cleaning, but it is always a fun project :) Thank you for reaching out!
