### ISSUE TITLE
Color Palette always selects bbr instead of bw

### ISSUE THREAD

**Issue by KreitnerL** [anibalsolon/vscode-neuro-viewer#14]
For all my scans the images are displayed with the bbr color palette instead of the usual bw.
![image](https://user-images.githubusercontent.com/33372140/146942599-492dc33d-7a29-4748-b15c-71ec349ef483.png)

The color palette is chosen based on the min value of the nifti file.
https://github.com/anibalsolon/vscode-neuro-viewer/blob/main/webview/nifti/index.ts#L24-L26

I would either like to see the standard bw scale being used or a button to switch the color palette.

**Comment by anibalsolon** [comment]
hey @Linus4world thank you! Would you mind generating a histogram of the image please? I'm planning to be able to adjust the scale, to increase contrast, but a palette picker should be faster for now.

**Comment by KreitnerL** [comment]
Here is a histogram of the ct scan. Note that there are some extreme outliers so I also attached a text file with all the values and their respective frequency.
[hist_values.txt](https://github.com/anibalsolon/vscode-neuro-viewer/files/7758245/hist_values.txt)

![hist](https://user-images.githubusercontent.com/33372140/146998982-21e0cfd4-d7a0-491d-97f6-a8b45bb258b7.png)

**Comment by anibalsolon** [comment]
Interesting! Yes, this scenario only thresholding can solve. Maybe it can do something more intelligent about it in the future, to identify these outliers. Please bear with me! 🔜 

As a workaround, you can highlight some of the data using the right histogram, by selecting a range there with the cursor (click and move).

**Comment by KreitnerL** [comment]
Great thanks for your support!

Yes, however, even if I select a range, I have no control over the color. It will either be displayed in blue, black, red or yellow

**Comment by anibalsolon** [comment]
Yes indeed- I've added two new options: a color picker and a fine-tuner. The color picker is a bit obvious, but the fine-tuner allows you to adjust the color range for the distribution of your data. In the example, the image has a long tail from outliers, so I adjusted the white thumb to a more reasonable place in the image distribution. LMK what you think and if it helps in your case.

![image](https://user-images.githubusercontent.com/562525/147304975-962bbe77-a0ed-4483-81dc-6614edbe2df3.png)

![image](https://user-images.githubusercontent.com/562525/147304997-ee709371-f78e-4142-a947-ac560addacc6.png)

**Comment by KreitnerL** [comment]
Yes perfect! That is exactly what I wanted. Thank you!
It would also be great if the extension could automatically save my preferences for the color palette so that I do not have to select it manually for every new sample.

**Comment by anibalsolon** [comment]
Yeah, that would be great indeed. I'll have to think better about the settings, and what would be the most user friendly solution. Other than global options, an option is to record the choices in the file using Nifti extensions (a XML-like payload stored in the end of the file).

I've opened an issue to track this: https://github.com/anibalsolon/vscode-neuro-viewer/issues/18

Thank again for the feedback!
