### ISSUE TITLE
Output appears empty

### ISSUE THREAD

**Issue by astewartau** [anibalsolon/vscode-neuro-viewer#25]
I tried using vscode-neuro-viewer with visual-studio-code-bin 1.64.2-1 on Arch Linux. 

This is the output after opening a file:

![image](https://user-images.githubusercontent.com/9957135/163115568-c95130a0-296b-4e56-8d67-54dff3a686fb.png)

The same thing has happened for all NIfTI files that I've tested. 

I can provide an example NIfTI file that failed for me (it is derived from publicly available data from the QSM Challenge 2.0): 

https://ufile.io/9t6rlyri

**Comment by anibalsolon** [comment]
Hi @astewartau thank you for the report and file! May I ask if you have the latest version of the extension?

I also wonder if it is some compatibility with Arch- maybe something shows up in the Developer Tools log? in `Help` → `Toogle Developer Tools`

**Comment by astewartau** [comment]
Hi @anibalsolon, yes I can confirm that it is version v0.0.11. 

This is output to the developer console when I try to open the NIfTI file - looks like problems with colours somehow?

```
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/f80445acd5a3dadef24aa209168452a3d97cc326/core/vs/workbench/workbench.desktop.main.js.map: Load canceled due to load timeout
workbench.desktop.main.js:75 [Extension Host] Open document file:///home/ashley/sub1snr1_ses-1_acq-qsm-E01_run-1_magnitude.nii
index.js:1 Uncaught Error: Invalid hex color: rgba(89, 152, 192, 0.93)
    at n.hexToRgb (index.js:1)
    at Object.833 (index.js:1)
    at o (index.js:1)
    at index.js:1
    at index.js:1
    at index.js:1
n.hexToRgb @ index.js:1
833 @ index.js:1
o @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
DevTools failed to load source map: Could not load content for https://file+.vscode-resource.vscode-webview.net/home/ashley/.vscode/extensions/anibalsolon.neuro-viewer-0.0.11/dist/webview/nifti/index.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
```

**Comment by anibalsolon** [comment]
Ah! Thank you @astewartau I'm glad the error showed up pretty clear. I believe your VSCode theme may be setting its colors using the `rgba` syntax instead of `hex`. The extension should handle this scenario.

I may be able to work on this and release a new version this weekend but lmk if you'd like to take a shot at it.

**Comment by anibalsolon** [comment]
Hi @astewartau thank you for your feedback and testing file- I've released a new version of the extension (v0.012), and it seems to be working! Please let me know if you have other issues.

**Comment by anibalsolon** [comment]
@astewartau let me know if you have more issues!

**Comment by astewartau** [comment]
Sorry for the delayed response - thanks so much for this! It's working well and I'll let you know if I have further issues.

**Comment by anibalsolon** [comment]
@astewartau happy to know, thank you! If you feel it could be improved in other ways, lmk
