### ISSUE TITLE
Use-case: Code Server in Docker/Singularity

### ISSUE THREAD

**Issue by TinasheMTapera** [anibalsolon/vscode-neuro-viewer#29]
Hi @anibalsolon, great plugin. I've used it and it works seamlessly in VSCode. I have a separate use-case to propose and see if it's in the scope of your work.

Our group uses [code-server](https://github.com/coder/code-server) on an HPC cluster which runs a VSCode backend in a singularity image, and forwards the port to a local machine. You can see how that's done [here in docker](https://easycode.page/code-server-vs-code-on-docker/) and [here in singularity](https://isaiahtaylor.medium.com/use-vs-code-on-a-supercomputer-15e4cbbb1bc2). Our use case is [here](https://pennlinc.github.io/docs/Basics/InterfacingWithClusters/).

Our current only limitation is that we cannot open images that are on the cluster with NeuroViewer. When we select an image, it hangs on the `Loading` screen.

Let me know if this is something you'd consider adding as a feature, or if there is anywhere you can point me to start digging around as to how you load images -- maybe I can PR.

Thanks!

**Comment by anibalsolon** [comment]
hey @TinasheMTapera thank you for the feedback- Let me ask you, is code-server the same as what Github uses in github.dev? If so, the last version of the extension is working there, maybe you can try to update the extension?

https://github.dev/Washington-University/HCPpipelines/blob/master/global/templates/MNI152_T1_2mm.nii.gz
After installing the extension, it looks like this:
![image](https://user-images.githubusercontent.com/562525/165558227-163018b3-8b8d-4868-b27e-09329f52a93c.png)

If not, I'll def look into it. This extension was mainly build to visualize images where it is harder to do so e.g. clusters.

**Comment by TinasheMTapera** [comment]
It looks to be the same architecture, yes! (Thanks for showing me that, I had no idea)

Unfortunately I'm having trouble installing the latest version. Within code-server, the latest available version of NeuroViewer is 0.0.9 as current. I'm not sure if perhaps there's some marketplace configuration I need to fix there, like in my extensions sidebar?

Alternatively, I tried to install from VSIX file, and instead got the error that 0.0.13 is unavailable for my version of `code-server`:

```
Singularity> code-server --version
4.2.0 693b1fac04524bb0e0cfbb93afc85702263329bb with Code 1.64.2
```

Note that this `code-server` instance was only installed and began running a couple of days ago, so it's pretty up-to-date.

Thoughts?

**Comment by anibalsolon** [comment]
Not sure! So from a brief research, I found out that it does not use the official marketplace, but the Open VSX one. The extension is in its last version there: https://open-vsx.org/extension/anibalsolon/neuro-viewer

It is weird that is saying it is unavailable, have you tried to directly install the .vsix file?
I've spun up a Docker code-server here, and it shows me the last extension version (0.0.13). Is is possible that it has some sort of cache on extension versions?

Nevertheless, I was able to reproduce your error (even with the last version). It happens because of the way it tries to download the interface files (javascript), a security feature is currently blocking it. I will try to figure this out and let you know!

**Comment by TinasheMTapera** [comment]
Thanks! Yes I have tried to directly install from vsix, and instead got the error that 0.0.13 is unavailable for my version of `code-server`.

```
Unable to install extension 'anibalsolon.neuro-viewer' as it is not compatible with VS Code '1.64.2'.
```

**Comment by TinasheMTapera** [comment]
Additionally (I guess somewhat important) is that I downloaded a bunch of different versions of VSIX files and was successfully able to install `0.0.10`, that's the highest version I got installed successfully but it still hangs at loading screen.

**Comment by anibalsolon** [comment]
@TinasheMTapera I've found out the issue, and that's mainly related on how the data was being loaded (using websockets). For now, I have turned to a less-optimal way, but one that is able to work in code-server without extra configuration.

Would you like to give it a try?
https://github.com/anibalsolon/vscode-neuro-viewer/releases/download/v0.0.14-4/neuro-viewer-0.0.14-4.vsix

**Comment by anibalsolon** [comment]
@TinasheMTapera if you still have issues, let me know!

**Comment by TinasheMTapera** [comment]
Hey @anibalsolon thanks for the ping, I think the challenge on our end is a permissions issue that's specific to our cluster, so their might not be anything we can do together about that! You can close this issue, thanks!

**Comment by anibalsolon** [comment]
@TinasheMTapera thanks for the follow up- would you know if it is permission that the extension requires to work? Maybe the extension can be changed in such a way that it does not require this permission. I'd be happy to help dig the issue, it is a good use case with `code-server`.

**Comment by TinasheMTapera** [comment]
It's a pretty narrow corner case, I believe https://pennlinc.github.io/docs/cubic#file-permissions-on-cubic

I wouldn't worry too much about it since our cluster is just a very odd case, but if you would like for me to get more detailed diagnostics let me know!
