### ISSUE TITLE
Possibility of publishing it to open-vsx.org?

### ISSUE THREAD

**Issue by SamGuay** [anibalsolon/vscode-neuro-viewer#6]
Hey Anibal! 

Great extension! I was happily surprised to see you were the author. I was feeling lazy and needed to look at a bunch of nifti files on a server so I used the [sshfs extension](https://open-vsx.org/extension/Kelvin/vscode-sshfs) with your extension and it worked like a charm. So this issue is more a request than a bug report. 

For _open_ and _libre_ reasons, I use VSCodium instead of VSCode, so I was wondering if you'd be willing to go for the extra mile and publish it to Open VSX in addition to the VS Code Marketplace? [Open VSX](https://open-vsx.org/) is an open-source registry for VS Code extensions. It can be used by any development environment that supports such extensions. 

I could install the extension by downloading the VSIX file, but it would be neat if NeuroViewer was directly on Open VSX! :) I have never published an extension myself, but I think it doesn't require much more from your side. Here's a [link to the wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension) explaining the publishing process.

Happy to help you in that regard if you need anything. 

Thanks again for your great extension :rocket:

**Comment by anibalsolon** [comment]
Hey @SamGuay !

Thanks, I am actually surprised someone is using it 😁 I use it for the same reason, I use remote-ssh, and moving files around to visualize them or even using X-forward is just sub-sub-sub-optimal for me. Glad it is working fine so far.

Yes, I can definitely support OpenVSX, no problemo! Thank you for the link. I was thinking about streamlining the deployment with Github Actions, maybe that what was missing for me to pull the trigger on it.

Just be aware that it might not fully support Nifti, but any problem should be clear during visualization. If you have any suggestions and bugs, just let me know! PRs are welcome too 😄

**Comment by anibalsolon** [comment]
@SamGuay I've done the process manually, to familiarize myself with it. You can now install it from [OpenVSX](https://open-vsx.org/extension/anibalsolon/neuro-viewer) (waiting on the namespace claiming process).

**Comment by anibalsolon** [comment]
Namespace claimed, good to go!

**Comment by SamGuay** [comment]
Waaa, thanks so much!! :fire:
